# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-11 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='productname',
            field=models.CharField(max_length=64),
        ),
    ]
