# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-17 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20200916_1639'),
        ('mainApp', '0008_auto_20200911_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_num', models.IntegerField(default=1)),
                ('is_select', models.BooleanField()),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Goods')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.User')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
